-- system.lua
--
-- This script is executed after a system boot or a system reset and is intended
-- to config Lua RTOS

-- DO NOT EDIT THIS FILE. TO CHANGE THE DEFAULT CONFIGURATIONS EDIT THE config.lua
-- FILE

-- Config table
config = {
	shell = true,
	history = true,	
	loglevel = os.LOG_INFO,
	logcons = true,
	wifi = false,
	ap = false,
	ethernet = false,
	sntp = false,
	http = false,
	openvpn = false,
	ssh = false,
	can = {
		gw = false
	},
	net = {
		wifi = nil,
		ethernet = nil
	},
	data = {}
}

-- Default wifi config
config.data.wifi = {
	ssid = "",
	pass = "",
	ip = nil,
	mask = nil,
	gw = nil,
	dns1 = nil,
	dns2 = nil
}

-- Default ethernet config
config.data.ethernet = {
	ssid = "",
	pass = "",
	ip = nil,
	mask = nil,
	gw = nil,
	dns1 = nil,
	dns2 = nil
}

-- HTTP server default config
config.data.http = {
	httpPort = 80,
	httpsPort = 0, 
	caFile = "",
	keyFile = ""
}

-- CAN gateway default config
config.data.can = {
	gw = {
		port = 1333,
		speed = 1000
	}
}

-- Load configution
dofile("config.lua")

if (config.wifi) then
	config.net.wifi = config.data.wifi
end

if (config.ethernet) then
	config.net.ethernet = config.data.ethernet
end

-- Network setup
if (config.wifi) then
	-- Provisioning: if net.wf.prov is available and no credentials are stored,
	-- start the captive-portal SoftAP (this call blocks until the device reboots).
	if (net.wf.prov ~= nil) then
		if (not net.wf.prov.has_credentials()) then
			print("No WiFi credentials found — starting provisioning portal ...")
			net.wf.prov.start("LuaRTOS-Setup", "")
			-- wifi_prov_start blocks until esp_restart() is called from the HTTP task.
		else
			-- Load stored credentials and override the config before connecting.
			local prov_ssid = {}
			local prov_pass = {}
			-- nvs.read returns the value for a given namespace/key
			local ok_ssid, stored_ssid = pcall(function()
				return nvs.read("wifiprov", "ssid")
			end)
			local ok_pass, stored_pass = pcall(function()
				return nvs.read("wifiprov", "pass")
			end)
			if ok_ssid and stored_ssid and stored_ssid ~= "" then
				config.net.wifi.ssid = stored_ssid
			end
			if ok_pass and stored_pass then
				config.net.wifi.pass = stored_pass
			end
		end
	end

	print("Starting wifi ...")
	net.wf.setup(
		net.wf.mode.STA, config.net.wifi.ssid, config.net.wifi.pass,
		config.net.wifi.ip, config.net.wifi.mask, config.net.wifi.gw,
		config.net.wifi.dns1, config.net.wifi.dns2
	)
	net.wf.start()
end

if (config.ethernet) then
	print("Starting ethernet ...")
	net.en.setup(
		config.net.ethernet.ip, config.net.ethernet.mask, config.net.ethernet.gw,
		config.net.ethernet.dns1, config.net.ethernet.dns2
	)
	net.en.start()
end

-- Start network services
if (config.sntp or config.openvpn or config.ssh) then
	print("Starting sntp client ...")
	net.service.sntp.start()
end

if (config.openvpn) then
	print("Starting openvpn client ...")
	net.service.openvpn.start()
end

if (config.ssh) then
	print("Starting ssh server ...")
	net.service.ssh.start()
end

if (config.http) then
	print("Starting http server ...")
	net.service.http.start(
		config.data.http.httpPort, config.data.http.httpsPort,
		config.data.http.caFile, config.data.http.keyFile
	)
end

if (config.can.gw) then
	net.service.can.start(can.CAN0, config.data.can.gw.speed, config.data.can.gw.port)
end

-- Main setups
os.shell(config.shell)
os.history(config.history)
os.loglevel(config.loglevel)
os.logcons(config.logcons)

config = nil